# Generated by Django 4.2.2 on 2023-06-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='fearured',
            new_name='featured',
        ),
    ]
