# Generated by Django 4.1.3 on 2023-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230206_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
