# Generated by Django 4.1.3 on 2023-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_booking_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
