# Generated by Django 4.1.3 on 2023-02-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='image',
            new_name='menu_image',
        ),
    ]
