# Generated by Django 4.1.3 on 2023-02-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_image_menu_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='base/files/items/'),
        ),
    ]
