# Generated by Django 4.2 on 2023-04-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooklistAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='BooklistAPI_price_a97067_idx',
            old_name='BooklistAPI_price_d862e1_idx',
        ),
    ]
