# Generated by Django 4.1.7 on 2023-08-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastname',
        ),
    ]
