# Generated by Django 4.1.7 on 2023-08-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0002_remove_account_email_remove_account_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
