# Generated by Django 4.1.7 on 2023-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0004_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#ff5c00', max_length=15),
        ),
    ]
